# Generated by Django 6.0.5 on 2026-06-03 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_comment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
