# Generated by Django 6.0.5 on 2026-06-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('AG', 'Agent'), ('US', 'Regular')], default='AG', max_length=2),
        ),
    ]
